{{- if .Values.investigator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-bug-agent.fullname" . }}-collector
  labels:
    {{- include "kube-bug-agent.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.investigator.kubernetes.enabled }}
{{- end }}
